name: lil_either
version: 1.0.0
description: The Either data type as an alternative to throwing exceptions
homepage: https://github.com/mit-73/little

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

dev_dependencies:
  test: ^1.17.4
