name: lil_auto_increment
version: 1.0.0
description: The library for creating generator function that does auto increment value
homepage: https://github.com/mit-73/little

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

dev_dependencies:
  test: ^1.17.4
